import type {Metadata} from 'next';
import {createServerClient} from '@/helpers/server-client';
import {AuthProvider} from './context';
import './globals.css';
import {tomatoGrotesk} from '@/assets/fonts';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerClient();

  const {
    data: {session},
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <body className={`${tomatoGrotesk.className} bg-white min-h-screen px-4`}>
        <AuthProvider accessToken={accessToken}>{children}</AuthProvider>
      </body>
    </html>
  );
}

export {metadata};
